# fly.toml file generated for code-to-screen on 2022-10-01T18:15:22+02:00

app = "code-to-screen"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
